Repository Niketkumardheeryan/ML-CaPsule, pull requests merged in 2021-06, with the labels that each got.

#47 CODE_OF CODUCT
  CODE_OF_CONDUCT.md
Labels: LGMSOC21

#58 Added Extract Text from PDF using Python
  Extract_Text_from_PDF_using_Python/Text_to_pdf.py.ipynb
  Extract_Text_from_PDF_using_Python/readme.md
Labels: LGMSOC21, 🟩 Level1

#82 Covid19 forecasting using Prophet(time-series model)#18
  Covid19 forecasting with prophet/Covid19_forecasting_with_prophet.ipynb
  Covid19 forecasting with prophet/README.md
  Covid19 forecasting with prophet/case_time_series.csv
Labels: LGMSOC21, 🟨 Level2

#80 Fist commit
  Different_types_of_scaling_Method/Different type of Scaling Method.ipynb
  Different_types_of_scaling_Method/README.md
Labels: LGMSOC21, 🟨 Level2

#89 Medical Charges for Smokers and Non-smokers
  Medical Charges for Smokers and Non-smoker/Medicine Charges.ipynb
  Medical Charges for Smokers and Non-smoker/insurance.csv
  Medical Charges for Smokers and Non-smoker/readme.md
Labels: LGMSOC21, 🟧 Level3

#96 Unique Chatbot using Python
  Unique Chatbot/Chatbot.ipynb
  Unique Chatbot/Images/chatbot.gif
  Unique Chatbot/README.md
  Unique Chatbot/_config.yml
  Unique Chatbot/chatbot.py
  Unique Chatbot/chatbot.txt
  Unique Chatbot/requirements.txt
Labels: LGMSOC21, 🟨 Level2

#106 Sentiment analysis for depression based on social media posts
  Sentiment analysis for depression based on social media posts/Dataset/sentiment_tweets3.csv
  Sentiment analysis for depression based on social media posts/Model/Depression_detection_tweets.ipynb
  Sentiment analysis for depression based on social media posts/README.md
Labels: LGMSOC21, 🟨 Level2

#109 Added one Sports analytics project | Issue #98
  Sports Analytics Project/Messi_vs_Ronaldo_An_Analytical_Debate.ipynb
  Sports Analytics Project/README.md
  Sports Analytics Project/assets/newplot (1).png
  Sports Analytics Project/assets/newplot (11).png
  Sports Analytics Project/assets/newplot (2).png
  Sports Analytics Project/assets/newplot (4).png
  Sports Analytics Project/assets/newplot (8).png
  Sports Analytics Project/assets/newplot (9).png
  Sports Analytics Project/assets/newplot.png
Labels: LGMSOC21, 🟧 Level3

#122 Notebook on numpy and its inbuilt functions
  NumPy - Basics/NumPy - Basics.ipynb
  NumPy - Basics/README.md
Labels: LGMSOC21, 🟨 Level2

#114 Deep learning Model for object detection
  Object Detection/README.md
  Object Detection/object_detection.ipynb
Labels: LGMSOC21, 🟨 Level2

#112 Weather prediction
  Weather Prediction/README.md
  Weather Prediction/delhi_dewpoint.csv
  Weather Prediction/weather_predication.ipynb
Labels: LGMSOC21, 🟨 Level2

#129 Created various plots using Matplotlib,Seaborn
  Various Plots using Matplot,Seaborn,Pandas/Readme.md
  Various Plots using Matplot,Seaborn,Pandas/Various_Plots_in_Matplotlib.ipynb
  Various Plots using Matplot,Seaborn,Pandas/Various_Plots_in_Seaborn.ipynb
  Various Plots using Matplot,Seaborn,Pandas/train.csv
  Various_Plots_in_Matplotlib.ipynb
Labels: LGMSOC21, 🟧 Level3

#131 Added files
  Movie-Recommendation-System/Collaborative Filtering Dummy Dataset.ipynb
  Movie-Recommendation-System/Movie Lens Collaborative Filtering.ipynb
  Movie-Recommendation-System/README.md
  Movie-Recommendation-System/dataset/README.txt
  Movie-Recommendation-System/dataset/links.csv
  Movie-Recommendation-System/dataset/movies.csv
  Movie-Recommendation-System/dataset/ratings.csv
  Movie-Recommendation-System/dataset/tags.csv
  Movie-Recommendation-System/dataset/toy_dataset.csv
Labels: LGMSOC21, 🟨 Level2
