Repository Niketkumardheeryan/ML-CaPsule, pull requests merged in 2021-07, with the labels that each got.

#138 Improve Readme.md file
  .github/workflows/build.yml
  README.md
  build_readme.py
  requirements.txt
Labels: LGMSOC21, 🟨 Level2

#158 Heart Predection
  Heart_Predection/HeartDisease.ipynb
  Heart_Predection/Readme.md
  Heart_Predection/heart.csv
Labels: LGMSOC21, 🟥 Level4

#152 EDA-and-Perform-Modelling-on-Ionosphere dataset
  EDA-and-Perform-Modelling-on-Ionosphere-Dataset-main/EDA and Perform modelling on Ionosphere dataset.ipynb
  EDA-and-Perform-Modelling-on-Ionosphere-Dataset-main/Ionosphere.csv
  EDA-and-Perform-Modelling-on-Ionosphere-Dataset-main/README.md
Labels: LGMSOC21, 🟥 Level4

#165 Heart Failure Prediction
  heart failure/HEART.csv
  heart failure/README.md
  heart failure/heart_fail.ipynb
Labels: LGMSOC21, 🟧 Level3

#166 Class Imbalance Problem Solved (SMOTE & ADASYN)
  Class Imbalance problem/README.md
  Class Imbalance problem/adasyn.ipynb
  Class Imbalance problem/image/adasyn_example_1.png
  Class Imbalance problem/image/adasyn_example_2.png
  Class Imbalance problem/image/adasyn_example_3.png
  Class Imbalance problem/image/smote_example.png
  Class Imbalance problem/image/smote_example_1.png
  Class Imbalance problem/image/smote_example_2.png
  Class Imbalance problem/image/smote_example_3.png
  Class Imbalance problem/requirements.txt
  Class Imbalance problem/smote.ipynb
Labels: LGMSOC21, 🟧 Level3

#174 Analysis of Temperature Rise in PMSM.
  Analysis_of_Temperature_Rise_in_PMSM.ipynb
  README.md updated file
Labels: LGMSOC21, 🟧 Level3
