Repository Niketkumardheeryan/ML-CaPsule, pull requests merged in 2022-04, with the labels that each got.

#356 Issue#347 Language Detection
  LanguageDetection/LanguageDetectionModel.ipynb
  LanguageDetection/README.MD
Labels: GSSoC22, Level2

#410 Skin Disease Predictor Added
  Skin Disease Predictor/README.md
  Skin Disease Predictor/skin-disease-inception.ipynb
Labels: GSSoC22, Level2

#330 Issue #322 cloud-readme.md created
  Cloud Details/Cloud-Readme.md
Labels: GSSoC22, Level1

#259 Rock Paper Scissors Python Game
  Rock Paper Scissors Python Game/README.md
  Rock Paper Scissors Python Game/RockPaperScissorsPythonGame.ipynb
  Rock Paper Scissors Python Game/rock_paper_scissors_python_game.py
Labels: GSSoC22, Level2

#385 Analyze Glassdoor data
  Gender Pay Gap Analysis/Glassdoor Gender Pay Gap.csv
  Gender Pay Gap Analysis/README.md
  Gender Pay Gap Analysis/analyze_gender_pay_gap.ipynb
Labels: GSSoC22, Level2

#426 Github Topic Scraper added
  GitHub Topic Scraper/Github_Repo_Topics_Scraper.ipynb
  GitHub Topic Scraper/README.md
  GitHub Topic Scraper/requirements.txt
Labels: GSSoC22, Level2

#443 NLTK Documentation added
  NLTK Documentation/NLTK.ipynb
  NLTK Documentation/README.md
Labels: GSSoC22
