Repository Niketkumardheeryan/ML-CaPsule, pull requests merged in 2024-10, with the labels that each got.

#1104 added Speech to image generator
  Speech-to-Image Generator/readme.md
  Speech-to-Image Generator/requirements.txt
  Speech-to-Image Generator/screenshot1.png
  Speech-to-Image Generator/screenshot2.png
  Speech-to-Image Generator/speech-text_image_generator.py
  Speech-to-Image Generator/speech-to-image.mp4
Labels: gssoc -ext, level2, hacktoberfest accepted

#1137 Update Best Python programs.txt
  Basics of the Python/Best Practices Questions and Solutions/Best Python programs.txt
Labels: gssoc-ext, level2

#1149 Update README.md added Stargazers and Forkers section
  README.md
Labels: gssoc-ext, level1

#1153 Weapon-Detection-System
  WEAPON-DETECTION-SYSTEM/.gitattributes
  WEAPON-DETECTION-SYSTEM/README.md
  WEAPON-DETECTION-SYSTEM/req.txt
  WEAPON-DETECTION-SYSTEM/weapon_detection.py
  WEAPON-DETECTION-SYSTEM/weapon_detection1.py
  WEAPON-DETECTION-SYSTEM/yolov3_testing.cfg
Labels: gssoc-ext, level1

#1165 Created issue-reminder workflow
  .github/workflows/issue-reminder.yml
Labels: gssoc-ext, level1

#1154 Update index.html
  Handwritten character recognition/templates/index.html
Labels: gssoc-ext, level1
