Repository Niketkumardheeryan/ML-CaPsule, pull requests merged in 2024-05, with the labels that each got.

#540 #539 Added CNN Implementation
  MNIST English Classification/CNN/.ipynb files/CNN_PyTorch.ipynb
  MNIST English Classification/CNN/.py files/CNN_PyTorch.py
  MNIST English Classification/Readme.md
Labels: gssoc

#577 Added more functions
  NumPy - Basics/NumPy - Basics.ipynb
Labels: gssoc, level1

#578 Autism Identification System #525
  Autism Identification System/Data.csv
  Autism Identification System/READme.md
  Autism Identification System/autism_identification_notebook.ipynb
Labels: gssoc, level2

#617 Pypi Package created and deployed, FIX ISSUE #244
  .DS_Store
  PyPI Package/.github/workflows/ci.yaml
  PyPI Package/.github/workflows/python-publish.yaml
  PyPI Package/.gitignore
  PyPI Package/README.md
  PyPI Package/pyproject.toml
  PyPI Package/requirements.txt
  PyPI Package/requirements_dev.txt
  PyPI Package/setup.cfg
  PyPI Package/setup.py
  PyPI Package/src/dbgenie.egg-info/PKG-INFO
  PyPI Package/src/dbgenie.egg-info/SOURCES.txt
  PyPI Package/src/dbgenie.egg-info/dependency_links.txt
  PyPI Package/src/dbgenie.egg-info/requires.txt
  PyPI Package/src/dbgenie.egg-info/top_level.txt
  PyPI Package/src/dbgenie2/__init__.py
  PyPI Package/src/dbgenie2/mongodb/__init__.py
  PyPI Package/src/dbgenie2/mongodb/mongocrud.py
  PyPI Package/src/dbgenie2/mysql/__init__.py
  PyPI Package/src/dbgenie2/mysql/mysqlcrud.py
  PyPI Package/src/dbgenie2/postgresql/__init__.py
  PyPI Package/src/dbgenie2/postgresql/postgrescrud.py
  PyPI Package/tests/integration/__init__.py
  PyPI Package/tests/integration/__pycache__/__init__.cpython-312.pyc
  PyPI Package/tests/integration/__pycache__/test_int.cpython-312-pytest-7.1.3.pyc
  PyPI Package/tests/integration/test_int.py
  PyPI Package/tests/unit/__init__.py
  PyPI Package/tests/unit/__pycache__/__init__.cpython-312.pyc
  PyPI Package/tests/unit/__pycache__/test_unit.cpython-312-pytest-7.1.3.pyc
  PyPI Package/tests/unit/test_unit.py
  PyPI Package/tox.ini
Labels: gssoc, level2

#631 Added Text Summarization Model.
  Text Summarization Model/Model/text_summary.ipynb
  Text Summarization Model/README.md
Labels: gssoc, level1

#636 Added complete project of chicken disease classification
  Chicken_Disease_Classification/Dockerfile
  Chicken_Disease_Classification/LICENSE
  Chicken_Disease_Classification/README.md
  Chicken_Disease_Classification/app.py
  Chicken_Disease_Classification/config/config.yaml
  Chicken_Disease_Classification/dvc.lock
  Chicken_Disease_Classification/dvc.yaml
  Chicken_Disease_Classification/inputImage.jpg
  Chicken_Disease_Classification/main.py
  Chicken_Disease_Classification/params.yaml
  Chicken_Disease_Classification/requirements.txt
  Chicken_Disease_Classification/research/01_data_ingestion.ipynb
  Chicken_Disease_Classification/research/02_prepare_base_model.ipynb
  Chicken_Disease_Classification/research/03_prepare_callbacks.ipynb
  Chicken_Disease_Classification/research/04_training.ipynb
  Chicken_Disease_Classification/research/05_model_evaluation_with_mlflow.ipynb
  Chicken_Disease_Classification/research/mlflow_exp/argv_demo.py
  Chicken_Disease_Classification/research/mlflow_exp/example.py
  Chicken_Disease_Classification/research/trials.ipynb
  Chicken_Disease_Classification/scores.json
  Chicken_Disease_Classification/setup.py
  Chicken_Disease_Classification/src/cnnClassifier/__init__.py
  Chicken_Disease_Classification/src/cnnClassifier/components/__init__.py
  Chicken_Disease_Classification/src/cnnClassifier/components/data_ingestion.py
  Chicken_Disease_Classification/src/cnnClassifier/components/evaluation.py
  Chicken_Disease_Classification/src/cnnClassifier/components/prepare_base_model.py
  Chicken_Disease_Classification/src/cnnClassifier/components/prepare_callbacks.py
  Chicken_Disease_Classification/src/cnnClassifier/components/training.py
  Chicken_Disease_Classification/src/cnnClassifier/config/__init__.py
  Chicken_Disease_Classification/src/cnnClassifier/config/configuration.py
  Chicken_Disease_Classification/src/cnnClassifier/constants/__init__.py
  Chicken_Disease_Classification/src/cnnClassifier/entity/__init__.py
  Chicken_Disease_Classification/src/cnnClassifier/entity/config_entity.py
  Chicken_Disease_Classification/src/cnnClassifier/pipeline/__init__.py
  Chicken_Disease_Classification/src/cnnClassifier/pipeline/predict.py
  Chicken_Disease_Classification/src/cnnClassifier/pipeline/stage_01_data_ingestion.py
  Chicken_Disease_Classification/src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
  Chicken_Disease_Classification/src/cnnClassifier/pipeline/stage_03_training.py
  Chicken_Disease_Classification/src/cnnClassifier/pipeline/stage_04_evaluation.py
  Chicken_Disease_Classification/src/cnnClassifier/utils/__init__.py
  Chicken_Disease_Classification/src/cnnClassifier/utils/common.py
  Chicken_Disease_Classification/template.py
  Chicken_Disease_Classification/templates/index.html
Labels: gssoc, level2

#655 Netflix power bi
  Basics of Power Bi/Netflix/Netflixcleaned.csv
  Basics of Power Bi/Netflix/Readme.md
  Basics of Power Bi/Netflix/image-1.png
  Basics of Power Bi/Netflix/image.png
  Basics of Power Bi/Netflix/netflix.pbix
Labels: gssoc, level1, level2

#687 Add Content: Pandas Basics
  Pandas-Basics/Datasets/Titanic.csv
  Pandas-Basics/Datasets/readme.md
  Pandas-Basics/Importing_and_Exporting_Data_in_Pandas.ipynb
  Pandas-Basics/Index.md
  Pandas-Basics/Introduction_to_Pandas_Library_and_DataFrames.ipynb
  Pandas-Basics/readme.md
Labels: gssoc, level1

#702 Improved bitcoin price prediction
  Bitcoin Price Predictor/Bitcoin_Price_Prediction.ipynb
Labels: gssoc, level1

#709 Create jupyter notebooks for python basics lecture files
  Basics of the Python/Basic of Python/2.TUPLES_LECTURE/DICTIONARIES.ipynb
  Basics of the Python/Basic of Python/2.TUPLES_LECTURE/LISTS_AND_RANGE.ipynb
  Basics of the Python/Basic of Python/2.TUPLES_LECTURE/PDF/DICTIONARIES.pdf
  Basics of the Python/Basic of Python/2.TUPLES_LECTURE/PDF/LISTS_EXERCISE.pdf
  Basics of the Python/Basic of Python/2.TUPLES_LECTURE/PDF/LIST_AND_RANGE.pdf
  Basics of the Python/Basic of Python/2.TUPLES_LECTURE/PDF/LIST_SOLUTIONS.pdf
  Basics of the Python/Basic of Python/2.TUPLES_LECTURE/PDF/TUPLES_LECTURE.pdf
  Basics of the Python/Basic of Python/2.TUPLES_LECTURE/TUPLES.ipynb
  Basics of the Python/Basic of Python/3.CONTROL_FLOW_SOLUTIONS/CONTROL_FLOW.ipynb
  Basics of the Python/Basic of Python/3.CONTROL_FLOW_SOLUTIONS/PDF/CONTROL_FLOW.pdf
  Basics of the Python/Basic of Python/3.CONTROL_FLOW_SOLUTIONS/PDF/CONTROL_FLOW_EXERCISE.pdf
  Basics of the Python/Basic of Python/3.CONTROL_FLOW_SOLUTIONS/PDF/CONTROL_FLOW_SOLUTIONS.pdf
  Basics of the Python/Basic of Python/4.WHILE_LOOPS/FOR_LOOPS.ipynb
  Basics of the Python/Basic of Python/4.WHILE_LOOPS/PDF/ADVANCED_LOOPS.pdf
  Basics of the Python/Basic of Python/4.WHILE_LOOPS/PDF/BPC.pdf
  Basics of the Python/Basic of Python/4.WHILE_LOOPS/PDF/CONTROL_FLOW_IN_LOOPS.pdf
  Basics of the Python/Basic of Python/4.WHILE_LOOPS/PDF/EXERCISE.pdf
  Basics of the Python/Basic of Python/4.WHILE_LOOPS/PDF/FOR_LOOPS.pdf
  Basics of the Python/Basic of Python/4.WHILE_LOOPS/PDF/SOLUTIONS.pdf
  Basics of the Python/Basic of Python/4.WHILE_LOOPS/PDF/WHILE_LOOPS.pdf
  Basics of the Python/Basic of Python/4.WHILE_LOOPS/WHILE_LOOPS.ipynb
  Basics of the Python/Basic of Python/5.LIST_COMPREHENSION/LIST_COMPREHENSION.ipynb
  Basics of the Python/Basic of Python/5.LIST_COMPREHENSION/PDF/COMPREHENSION_EXERCISE.pdf
  Basics of the Python/Basic of Python/5.LIST_COMPREHENSION/PDF/COMPREHENSION_SOLUTIONS.pdf
  Basics of the Python/Basic of Python/5.LIST_COMPREHENSION/PDF/LIST_COMPREHENSION.pdf
  Basics of the Python/Basic of Python/6.FUNCTIONS_LECTURE/BUILT_IN_FUNCTIONS.ipynb
  Basics of the Python/Basic of Python/6.FUNCTIONS_LECTURE/FUNCTIONS.ipynb
  Basics of the Python/Basic of Python/6.FUNCTIONS_LECTURE/PDF/BUILT_IN_FUNCTIONS.pdf
  Basics of the Python/Basic of Python/6.FUNCTIONS_LECTURE/PDF/FUNCTIONS_EXERCISE.pdf
  Basics of the Python/Basic of Python/6.FUNCTIONS_LECTURE/PDF/FUNCTIONS_LECTURE.pdf
  Basics of the Python/Basic of Python/6.FUNCTIONS_LECTURE/PDF/FUNCTIONS_SOLUTIONS.pdf
  Basics of the Python/Basic of Python/6.FUNCTIONS_LECTURE/PDF/RANDOM_LECTURE1.pdf
  Basics of the Python/Basic of Python/7.LAMBDA/LAMBDA.ipynb
  Basics of the Python/Basic of Python/7.LAMBDA/PDF/ERRORS_EXERCISE.pdf
  Basics of the Python/Basic of Python/7.LAMBDA/PDF/ERRORS_SOLUTIONS.pdf
  Basics of the Python/Basic of Python/7.LAMBDA/PDF/LAMBDA.pdf
  Basics of the Python/Basic of Python/7.LAMBDA/PDF/TRY_EXCEPT_AND_FINALLY.pdf
  Basics of the Python/Basic of Python/8.FILES_SECTION/FILES.ipynb
  Basics of the Python/Basic of Python/8.FILES_SECTION/PDF/FILES_EXERCISE.pdf
  Basics of the Python/Basic of Python/8.FILES_SECTION/PDF/FILES_LECTURE.pdf
  Basics of the Python/Basic of Python/8.FILES_SECTION/PDF/FILE_SOLUTIONS.pdf
  Basics of the Python/Basic of Python/8.FILES_SECTION/skynet.txt
Labels: gssoc, level1
