Repository Niketkumardheeryan/ML-CaPsule, pull requests merged in 2024-07, with the labels that each got.

#872 Chi-Square Test
  Chi-Square Test/Chi_Square_Test.ipynb
  Chi-Square Test/dataset.csv
  Chi-Square Test/readme.md
  Chi-Square Test/requirement.txt
Labels: gssoc, level1

#891 Loan Repayment Prediction
  Loan Repayment Prediction/Loan_Repayment_Prediction.ipynb
  Loan Repayment Prediction/README.md
  Loan Repayment Prediction/loan_data.csv
Labels: gssoc, level2

#799 Document scanner
  Document Scanner/DocumentScan.ipynb
  Document Scanner/README.md
  Document Scanner/image/IMG-2012.jpg
Labels: gssoc, level2

#898 Added Chronic kidney disease
  Chronic Kidney Disease Prediction/Chronic_kidney_disease_prediction.ipynb
  Chronic Kidney Disease Prediction/Readme.md
  Chronic Kidney Disease Prediction/kidney_disease_dataset.csv
Labels: gssoc, level3

#927 added employee attrition prediction using Machine learning
  Employee_attrittion_prediction_using_ML/dataset/employee_attrition_data.csv
  Employee_attrittion_prediction_using_ML/images/box_plot-1.png
  Employee_attrittion_prediction_using_ML/images/box_plot-2.png
  Employee_attrittion_prediction_using_ML/images/correaltion_matrix.png
  Employee_attrittion_prediction_using_ML/images/count_plot.png
  Employee_attrittion_prediction_using_ML/images/gbm_cm.png
  Employee_attrittion_prediction_using_ML/images/histogram.png
  Employee_attrittion_prediction_using_ML/images/knn_cm.png
  Employee_attrittion_prediction_using_ML/images/pair_plot.png
  Employee_attrittion_prediction_using_ML/images/pie_chart-2.png
  Employee_attrittion_prediction_using_ML/images/pie_chart-3.png
  Employee_attrittion_prediction_using_ML/images/piechart-1.png
  Employee_attrittion_prediction_using_ML/images/rf_cm.png
  Employee_attrittion_prediction_using_ML/images/scatter_plot.png
  Employee_attrittion_prediction_using_ML/images/violin_plot.png
  Employee_attrittion_prediction_using_ML/images/xgboost_cm.png
  Employee_attrittion_prediction_using_ML/model/app.py
  Employee_attrittion_prediction_using_ML/model/employee_attrition_prediction.ipynb
  Employee_attrittion_prediction_using_ML/model/knn_model.pkl
  Employee_attrittion_prediction_using_ML/readme.md
  Employee_attrittion_prediction_using_ML/requirements.txt
  Employee_attrittion_prediction_using_ML/webapp/webapp.mp4
Labels: gssoc, level3

#938 added Company Bankruptcy Using unsupervised
  Company Bankruptcy Using unsupervised/Bank Customer Segmentation using K means,DBCAN.ipynb
  Company Bankruptcy Using unsupervised/readme.md
  Company Bankruptcy Using unsupervised/requirement.txt
  Company Bankruptcy Using unsupervised/result.png
  Company Bankruptcy Using unsupervised/result1.png
Labels: gssoc, level3

#947 Infant Health Prediction
  Infant_Health_Prediction/Infant_Health_Prediction.ipynb
  Infant_Health_Prediction/README.md
  Infant_Health_Prediction/Synthetic-Infant-Health-Data.csv
Labels: gssoc, level2

#949 Addition of Artificial neural network Implementation from Scratch .
  Artifical neural network from scratch/README.md
  Artifical neural network from scratch/main.ipynb.ipynb
  Artifical neural network from scratch/requirements.txt
Labels: gssoc, level1

#945 Molecule Property Analysis using GNN
  Molecule_Property_Analysis/README.md
  Molecule_Property_Analysis/__pycache__/mpl_rdkit_utils.cpython-311.pyc
  Molecule_Property_Analysis/best_val.model
  Molecule_Property_Analysis/input.csv
  Molecule_Property_Analysis/input.smi
  Molecule_Property_Analysis/molecule_property_analysis.ipynb
  Molecule_Property_Analysis/mpl_rdkit_utils.py
Labels: gssoc, level2

#785 Indian Currency Notes Classification
  Indian Currency Detection using DL/Dataset/README.md
  Indian Currency Detection using DL/Images/DenseNet121/09ec2435-528f-467a-886c-5a6c563778c0.png
  Indian Currency Detection using DL/Images/DenseNet121/1aeba4fe-e49c-4f98-a78c-863e9105a6a8.png
  Indian Currency Detection using DL/Images/DenseNet121/43981767-5776-4649-bc6e-bee34ffac39c.png
  Indian Currency Detection using DL/Images/InceptionV3_predictions/32abcdf1-3a32-4a63-97ae-2500dee9bbb3.png
  Indian Currency Detection using DL/Images/InceptionV3_predictions/72d2062d-41f0-4455-9607-f437b4362a51.png
  Indian Currency Detection using DL/Images/InceptionV3_predictions/988c3a1f-cd99-4d61-b395-0b2617891bea.png
  Indian Currency Detection using DL/Images/NASNetMobile_predictions/28cea739-a49a-452d-8796-6d3069780991.png
  Indian Currency Detection using DL/Images/NASNetMobile_predictions/2e4cba78-0b17-4c85-9ee0-7bdd3522b9d1.png
  Indian Currency Detection using DL/Images/NASNetMobile_predictions/df1812d9-3e50-4de0-9024-af9d2f54d16e.png
  Indian Currency Detection using DL/Images/Resnet50V2_predictions/7cf8ba06-bb9e-4f23-9e39-c59923f3f300.png
  Indian Currency Detection using DL/Images/Resnet50V2_predictions/994bb09c-443a-4f94-a2b2-8457e0875228.png
  Indian Currency Detection using DL/Images/Resnet50V2_predictions/ce0ab66b-583d-4966-8848-bbe2032d5060.png
  Indian Currency Detection using DL/Images/Xception_predictions/1ee80672-8bf2-4946-a8c4-0c742949ae70.png
  Indian Currency Detection using DL/Images/Xception_predictions/5ddb2db6-6493-472e-9fb2-3510b6e214a2.png
  Indian Currency Detection using DL/Images/Xception_predictions/85aaddd6-dd79-42ad-b209-33f89cc5ff18.png
  Indian Currency Detection using DL/Images/bar.png
  Indian Currency Detection using DL/Images/image_path.png
  Indian Currency Detection using DL/Images/pie.png
  Indian Currency Detection using DL/Models/models_IndianCurrencyDetection.ipynb
  Indian Currency Detection using DL/README.md
  Indian Currency Detection using DL/requirement.txt
Labels: gssoc, level2

#913 Basic Visualization in R
  R language/Basic Visualization/Bar Chart.R
  R language/Basic Visualization/Box Plot.R
  R language/Basic Visualization/Histogram.R
  R language/Basic Visualization/Line Chart.R
  R language/Basic Visualization/Pie Chart.R
  R language/Basic Visualization/Plots/Bar_Chart.png
  R language/Basic Visualization/Plots/Box_Plot.png
  R language/Basic Visualization/Plots/Histogram.png
  R language/Basic Visualization/Plots/Line_Chart.png
  R language/Basic Visualization/Plots/Pie_Chart.png
  R language/Basic Visualization/Plots/Scatter Plot.png
  R language/Basic Visualization/README.md
  R language/Basic Visualization/Scatter Plot.R
Labels: gssoc, level2

#952 Added Smart Phone Processor classification
  Smartphone processor classification/Images/Matrix model 1.png
  Smartphone processor classification/Images/Matrix model 2.png
  Smartphone processor classification/Images/Visualization model 1.png
  Smartphone processor classification/Images/Visualization model 2.png
  Smartphone processor classification/Images/Visualization model 3.png
  Smartphone processor classification/Images/matrix model 3.png
  Smartphone processor classification/dataset/ML_ALL_benchmarks.csv
  Smartphone processor classification/dataset/antutu_android_vs_ios_v4.csv
  Smartphone processor classification/dataset/smartphone_cpu_stats.csv
  Smartphone processor classification/model/ML_ALL_benchmarks.csv
  Smartphone processor classification/model/Ranking.ipynb
  Smartphone processor classification/readme.md
  Smartphone processor classification/requirements.txt
Labels: gssoc, level2

#962 Added Crude oil forecasting
  Crude oil forecasting/Readme.md
  Crude oil forecasting/crudeoil.ipynb
  Crude oil forecasting/dataset.csv
Labels: gssoc, level2

#994 Added Engineering career Role prediction using Machine Learning
  Engineering Career Role Prediction/Engineering_career_role.csv
  Engineering Career Role Prediction/Engineering_career_role_prediction.ipynb
  Engineering Career Role Prediction/app.py
  Engineering Career Role Prediction/images/cm_gbm.png
  Engineering Career Role Prediction/images/cm_logistic.png
  Engineering Career Role Prediction/images/cm_naive_bayes.png
  Engineering Career Role Prediction/images/cm_rf.png
  Engineering Career Role Prediction/images/count plot-2.png
  Engineering Career Role Prediction/images/count plot.png
  Engineering Career Role Prediction/images/histogram-1.png
  Engineering Career Role Prediction/images/histogram-2.png
  Engineering Career Role Prediction/images/pie-chart-1.png
  Engineering Career Role Prediction/images/piechart-2 (1).png
  Engineering Career Role Prediction/images/piechart-3.png
  Engineering Career Role Prediction/images/prediction_on_custom_input.png
  Engineering Career Role Prediction/images/violin-plot.png
  Engineering Career Role Prediction/logistic.pkl
  Engineering Career Role Prediction/readme.md
  Engineering Career Role Prediction/requirements.txt
  Engineering Career Role Prediction/webapp.mp4
Labels: gssoc, level2

#991 Algorithmic_Trading_Strategy_Optimization_Using_Genetic_Algorithms added
  Algorithmic_Trading_Strategy_Optimization_Using_Genetic_Algorithms/Algorithmic_Trading_Strategy_Optimization_Using_Genetic_Algorithms (1).ipynb
  Algorithmic_Trading_Strategy_Optimization_Using_Genetic_Algorithms/readme.md
  Algorithmic_Trading_Strategy_Optimization_Using_Genetic_Algorithms/trading_data.csv
Labels: gssoc, level2

#819 Statistical modeling using pycaret and AutoMl
  Statistical_modeling_python/README.md
  Statistical_modeling_python/Statistical_modeling.ipynb
  Statistical_modeling_python/requirements.txt
  Statistical_modeling_python/retail_sales_dataset.csv
  Statistical_modeling_python/stats_modelling.ipynb
Labels: gssoc, level1

#961 Added Foreign Exchange Rate Prediction
  Foreign Exchange Rate Prediction/Foreign_Exchange_Rates.csv
  Foreign Exchange Rate Prediction/LSTM_model.ipynb
  Foreign Exchange Rate Prediction/Readme.md
Labels: gssoc, level1

#966 Indian Elections added
  Indian Elections/Election_prediction-WebApp/LS_2.0.csv
  Indian Elections/Election_prediction-WebApp/Readme.md
  Indian Elections/Election_prediction-WebApp/app.py
  Indian Elections/Election_prediction-WebApp/images.jpeg
  Indian Elections/README.md
  Indian Elections/generalelections.ipynb
Labels: gssoc, level2

#967 Feature Selection using Genetic ALgorithm added
  Feature Selection using Genetic ALgorithm/Feature_Selection_for_Machine_Learning_with_Genetic_Algorithm.ipynb
  Feature Selection using Genetic ALgorithm/readme.md
  Feature Selection using Genetic ALgorithm/requirement.txt
Labels: gssoc, level2

#988 Grad cam visualizer files have been added
  GRAD-CAM-Visualizer/GRAD_CAM_Visualizer.ipynb
  GRAD-CAM-Visualizer/README.md
  GRAD-CAM-Visualizer/dog_and_cat.png
Labels: gssoc, level1

#1006 PortFolio Optimaization Using Genetic ALgorithm added
  PortFolio Optimaization Using Genetic ALgorithm/Portfolio_Optimization_Using_Genetic_Algorithm.ipynb
  PortFolio Optimaization Using Genetic ALgorithm/image.png
  PortFolio Optimaization Using Genetic ALgorithm/portfolio_data.csv
  PortFolio Optimaization Using Genetic ALgorithm/readme.md
Labels: gssoc, level2

#1021 Added learning rules in ANN
  Learning Rules In ANN/Learning-Rules.md
  Learning Rules In ANN/learning_rules.ipynb
Labels: gssoc, level1

#1018 Pension Fund Optimization added
  Pension Fund Optimization/PensionFundOptimization.ipynb
  Pension Fund Optimization/pension_fund_data.csv
  Pension Fund Optimization/readme.md
Labels: gssoc, level2

#863 Add AI Virtual Drag and Drop project using OpenCV
  Virtual Drag and Drop Using OpenCV/gates.jpg
  Virtual Drag and Drop Using OpenCV/virtualDragDrop.py
Labels: gssoc, level2

#875 Image Stitching Project using OpenCV library
  Image Stitching/Dataset/Glacier/CIMG4017.JPG
  Image Stitching/Dataset/Glacier/CIMG4018.JPG
  Image Stitching/Dataset/Mountain/hill1.jpg
  Image Stitching/Dataset/Mountain/hill2.jpg
  Image Stitching/README.md
  Image Stitching/Result/Glacier/output1.jpg
  Image Stitching/Result/Glacier/output2.jpg
  Image Stitching/Result/Mountain/output1.jpg
  Image Stitching/Result/Mountain/output2.jpg
  Image Stitching/stitching.ipynb
Labels: gssoc, level2

#973 Web Traffic Time Series Forecasting
  Web Traffic Time series forecasting/README.md
  Web Traffic Time series forecasting/Web_Traffic_Time_series_Forecast.ipynb
Labels: gssoc, level1

#1013 Dynamic Hedging Strategies using Reinforcement Learning added
  Dynamic Hedging Strategies using Reinforcement Learning/Dynamic_Hedging_StrategiesReinforcementLear.ipynb
  Dynamic Hedging Strategies using Reinforcement Learning/dqn_agent.h5
  Dynamic Hedging Strategies using Reinforcement Learning/readme.md
  Dynamic Hedging Strategies using Reinforcement Learning/requirement.txt
Labels: gssoc, level2

#1003 Create a new Improved Readme.md file for ML capsule #989
  README.md
Labels: gssoc, level2

#1022 Added Perceptron Network
  Perceptron From Scratch/perceptron.ipynb
  Perceptron From Scratch/readmd.md
Labels: gssoc, level1
