Repository Niketkumardheeryan/ML-CaPsule, pull requests merged in 2024-06, with the labels that each got.

#742 [Project Addition] : Sports Image Classification
  Sports Image Classification/Dataset/README.md
  Sports Image Classification/Images/EfficientNetB0_predictions/237b28b0-74e7-44cd-9190-a8e1c74583e6.png
  Sports Image Classification/Images/EfficientNetB0_predictions/600e20be-02c2-4e34-afc5-8255fe7ceb0e.png
  Sports Image Classification/Images/EfficientNetB0_predictions/e97f3a99-06ab-4091-a4cb-0c52e0f8e266.png
  Sports Image Classification/Images/EfficientNetB0_predictions/edd61747-0a67-4e44-8ac8-575db0ed883b.png
  Sports Image Classification/Images/EfficientNetB0_predictions/f0b4cc0c-bc35-4aef-b44b-9c83a2cf237c.png
  Sports Image Classification/Images/EfficientNetB0_predictions/f932a305-059d-46a9-aa04-6b6df6b8bbe9.png
  Sports Image Classification/Images/InceptionV3_predictions/014c8af8-227e-4d13-82e8-4d3c016c176a.png
  Sports Image Classification/Images/InceptionV3_predictions/3493d4e5-7b47-40fd-b884-b78a89dbe05b.png
  Sports Image Classification/Images/InceptionV3_predictions/8e9e4340-411d-46eb-9ad5-ab186f17b33b.png
  Sports Image Classification/Images/InceptionV3_predictions/a0278af7-ad0c-49e7-b5c2-c38424b016a6.png
  Sports Image Classification/Images/InceptionV3_predictions/d262930f-e7a6-47dd-afa1-6e79326090a2.png
  Sports Image Classification/Images/InceptionV3_predictions/dc89f4e9-3240-4dc6-be77-cb9cba0f2a9d.png
  Sports Image Classification/Images/MobieNetV2_predictions/2e6ecbbe-9f01-476d-af15-c578354d8260.png
  Sports Image Classification/Images/MobieNetV2_predictions/318512f5-a8d1-4e6b-bb4b-4aa52a7c5378.png
  Sports Image Classification/Images/MobieNetV2_predictions/3fdb3807-57fe-4b71-81d8-55dcc7b0fe9f.png
  Sports Image Classification/Images/MobieNetV2_predictions/63b4f459-bcba-47c0-ab6d-e046dca169da.png
  Sports Image Classification/Images/MobieNetV2_predictions/7d36752a-3c3b-4cbb-b5c1-6c662f4a8723.png
  Sports Image Classification/Images/MobieNetV2_predictions/accuracy.png
  Sports Image Classification/Images/MobieNetV2_predictions/ec836a26-e5f3-4e07-81ca-9cedb60bdee8.png
  Sports Image Classification/Images/Resnet50_predictions/322db5d3-7d52-4f54-8268-bea5d55feaf8.png
  Sports Image Classification/Images/Resnet50_predictions/3aa5211a-80d4-45f7-9f93-7fa4f32c1a71.png
  Sports Image Classification/Images/Resnet50_predictions/592f11ba-fb41-44e6-bd5e-b26f4ee3b34a.png
  Sports Image Classification/Images/Resnet50_predictions/62cf99c4-c8a4-4331-a4ad-607adc532d87.png
  Sports Image Classification/Images/Resnet50_predictions/653173c2-ef01-4fba-bb58-78e740dd71b5.png
  Sports Image Classification/Images/Resnet50_predictions/dbde1cae-6337-4236-af24-65f557592867.png
  Sports Image Classification/Images/Xception_predictions/162c7eb0-4671-4991-9f75-5345cc1854f6.png
  Sports Image Classification/Images/Xception_predictions/1e3161aa-d016-4e9a-900e-3cc5f11be2ee.png
  Sports Image Classification/Images/Xception_predictions/3f6d756f-917b-45a8-ba53-86a96b56bb2d.png
  Sports Image Classification/Images/Xception_predictions/49a7b8a8-b8f1-481d-9094-0edce1ac8932.png
  Sports Image Classification/Images/Xception_predictions/8132406e-b77e-4497-83a8-7b10d1aacd27.png
  Sports Image Classification/Images/Xception_predictions/Accuracy.png
  Sports Image Classification/Images/Xception_predictions/a6e78b79-83a2-4c28-bd2c-dcefbd858f97.png
  Sports Image Classification/Images/bar.png
  Sports Image Classification/Images/image_path_distribution.png
  Sports Image Classification/Images/pie-chart.png
  Sports Image Classification/Models/README.md
  Sports Image Classification/Models/models_SportsImageClassification_final.ipynb
  Sports Image Classification/requirement.txt
Labels: gssoc, level3

#694 Added Disease_prediction
  Diseases_Prediction/.ipynb_checkpoints/Diseases_Prediction-checkpoint.ipynb
  Diseases_Prediction/Diseases_Prediction.ipynb
  Diseases_Prediction/Readme.md
  Diseases_Prediction/Testing.csv
  Diseases_Prediction/Training.csv
  Diseases_Prediction/catboost_info/catboost_training.json
  Diseases_Prediction/catboost_info/learn/events.out.tfevents
  Diseases_Prediction/catboost_info/learn_error.tsv
  Diseases_Prediction/catboost_info/time_left.tsv
  Diseases_Prediction/requirements.txt
Labels: gssoc, level2

#557 Created Brain Tumor Detection.
  Brain Tumor Detection/Dataset/README.md
  Brain Tumor Detection/Images/README.md
  Brain Tumor Detection/Images/image-1.png
  Brain Tumor Detection/Images/image-10.png
  Brain Tumor Detection/Images/image-11.png
  Brain Tumor Detection/Images/image-2.png
  Brain Tumor Detection/Images/image-3.png
  Brain Tumor Detection/Images/image-4.png
  Brain Tumor Detection/Images/image-5.png
  Brain Tumor Detection/Images/image-6.png
  Brain Tumor Detection/Images/image-7.png
  Brain Tumor Detection/Images/image-8.png
  Brain Tumor Detection/Images/image-9.png
  Brain Tumor Detection/Images/image.png
  Brain Tumor Detection/Images/image12.png
  Brain Tumor Detection/Model/README.md
  Brain Tumor Detection/Model/brain_tumor_model.ipynb
  Brain Tumor Detection/README.md
  Brain Tumor Detection/Web App/Final.mp4
  Brain Tumor Detection/Web App/README.md
  Brain Tumor Detection/Web App/Screenshot 2024-05-13 221628.png
  Brain Tumor Detection/Web App/app.py
  Brain Tumor Detection/Web App/requirements.txt
  Brain Tumor Detection/Web App/styles/styles.css
  Brain Tumor Detection/Web App/styles/styles1.css
  Brain Tumor Detection/Web App/templates/error.html
  Brain Tumor Detection/Web App/templates/index.html
  Brain Tumor Detection/Web App/templates/result.html
  Brain Tumor Detection/requirements.txt
Labels: gssoc, level3

#683 Adding more data cleaning techniques in the specified folder
  Data Filling and Cleaning Techniques/Data Cleaning-7 KNN-imputer.ipynb
  Data Filling and Cleaning Techniques/Data Cleaning-8 One_Hot_Encoding.ipynb
  Data Filling and Cleaning Techniques/Data Cleaning-9 random_sample_imputation.ipynb
  Data Filling and Cleaning Techniques/README.md
  Data Filling and Cleaning Techniques/train.csv
Labels: gssoc, level1

#679 Readme updated
  README.md
Labels: gssoc, level1

#677 Resume screening
  Resume screening/Dataset/README.md
  Resume screening/Model/Resume_screening.ipynb
  Resume screening/README.md
Labels: gssoc, level2

#676 Added issues templates
  .github/ISSUES_TEMPLATE/bug_report.md
  .github/ISSUES_TEMPLATE/documentation.md
  .github/ISSUES_TEMPLATE/feature_request.md
Labels: gssoc, level1

#669 [FEAT #527] : added plant disease prediction model
  Plant Disease Prediction/README.md
  Plant Disease Prediction/disease-prediction/model.ipynb
  Plant Disease Prediction/image-1.png
  Plant Disease Prediction/image-3.png
  Plant Disease Prediction/image.png
  Plant Disease Prediction/model/1/fingerprint.pb
  Plant Disease Prediction/model/1/keras_metadata.pb
  Plant Disease Prediction/model/1/saved_model.pb
  Plant Disease Prediction/tf_lite_model.tflite
  Plant Disease Prediction/tf_lite_quantized_model.tflite
Labels: gssoc, level2

#665 QnA Conversational Agent
  QnA Conversational Agent/PDFChat.ipynb
  QnA Conversational Agent/readme.md
  QnA Conversational Agent/requirements.txt
Labels: gssoc, level3

#664 Student Marks Prediction model added
  StudentMarksPrediction/README.md
  StudentMarksPrediction/Student_Marks.csv
  StudentMarksPrediction/StudentsMarksPrediction (1).ipynb
Labels: gssoc, level2

#689 Loan Prediction Project
  Loan-Prediction-main/Loan-Prediction-main/LoanPreds.ipynb
  Loan-Prediction-main/Loan-Prediction-main/README.md
  Loan-Prediction-main/Loan-Prediction-main/app.py
  Loan-Prediction-main/Loan-Prediction-main/loan-test.csv
  Loan-Prediction-main/Loan-Prediction-main/loan-train.csv
  Loan-Prediction-main/Loan-Prediction-main/models/model.pkl
  Loan-Prediction-main/Loan-Prediction-main/templates/index.html
Labels: gssoc, level2

#693 Analyzing Restaurant Reviews Using NLP #674
  Restaurant Review NLP/readme.md
  Restaurant Review NLP/restaurant-review-nlp.ipynb
Labels: gssoc, level1

#705 Add Deepfake Image Analyzer
  Deepfake_image_analyzer/README.md
  Deepfake_image_analyzer/cnn_image_classifier.ipynb
  Deepfake_image_analyzer/knn_image_classifier.ipynb
  Deepfake_image_analyzer/randomforest_image_classifier.ipynb
  Deepfake_image_analyzer/svm_image_classifier.ipynb
Labels: gssoc, level2

#724 Add Project on Impact of Feature Scaling with Comparative EDA and Best Practices
  Feature Scaling Techniques/Data_Preprocessing_project.ipynb
  Feature Scaling Techniques/README.md
  Feature Scaling Techniques/Social_Network_Ads.csv
Labels: gssoc

#733 K means
  K Means Clustering/.ipynb_checkpoints/Customer Segmentation and Marketing Strategy with KMeans Clustering-checkpoint.ipynb
  K Means Clustering/.ipynb_checkpoints/Mall_Customers-checkpoint.csv
  K Means Clustering/.ipynb_checkpoints/README-checkpoint.md
  K Means Clustering/.ipynb_checkpoints/output-checkpoint.png
  K Means Clustering/Customer Segmentation and Marketing Strategy with KMeans Clustering.ipynb
  K Means Clustering/Mall_Customers.csv
  K Means Clustering/README.md
  K Means Clustering/output.png
Labels: gssoc, level2

#735 Auto Commenting when a PR is merged
  .github/workflows/auto-comment-pr-merge.yml
Labels: gssoc, level1

#524 Add files via upload
  Rating_Prediction/IMDb Movies India.csv
  Rating_Prediction/Movie_Rating_Prediction (1).ipynb
  Rating_Prediction/README.md
Labels: gssoc, level2

#632 PR for Ultimate Housing Prediction Project #541
  Housing_Prediction/Dataset/housing.csv
  Housing_Prediction/Model/des_tree.pkl
  Housing_Prediction/Model/lin_reg.pkl
  Housing_Prediction/Readme.md
  Housing_Prediction/main_housing.ipynb
Labels: gssoc, level2

#721 Facerecognition: updated deepface.ipynb
  face-recognition/Readme.md
  face-recognition/db/ds_vggface_opencv_v2.pkl
  face-recognition/db/img2.jpg
  face-recognition/deepface.ipynb
  face-recognition/img1.jpg
  face-recognition/img2.jpg
  face-recognition/requirements.txt
Labels: gssoc, level2

#747 Added Online payment fraud detection model
  OnlinePaymentFraudDetection/PaymentFraudDetection.ipynb
  OnlinePaymentFraudDetection/Readme.md
Labels: gssoc, level2

#756 [Project Addition]: Breast Cancer Detection using DL - with Web App #737
  Breast Cancer Detection using DL with Webapp/Dataset/README.md
  Breast Cancer Detection using DL with Webapp/Images/Confusion Matrices.png
  Breast Cancer Detection using DL with Webapp/Images/Demo webpage.png
  Breast Cancer Detection using DL with Webapp/Images/MLP.png
  Breast Cancer Detection using DL with Webapp/Images/ResNet50.png
  Breast Cancer Detection using DL with Webapp/Images/VGG16.png
  Breast Cancer Detection using DL with Webapp/Model/Model.ipynb
  Breast Cancer Detection using DL with Webapp/Model/README.md
  Breast Cancer Detection using DL with Webapp/README.md
  Breast Cancer Detection using DL with Webapp/Webapp/README.md
  Breast Cancer Detection using DL with Webapp/Webapp/Recording 2024-06-01 212208.mp4
  Breast Cancer Detection using DL with Webapp/Webapp/static/style.css
  Breast Cancer Detection using DL with Webapp/Webapp/templates/index.html
  Breast Cancer Detection using DL with Webapp/Webapp/webapp.py
  Breast Cancer Detection using DL with Webapp/requirements.txt
Labels: gssoc, level3

#763 Added Feature Engineering
  Feature-Engineering/Feature_Engineering.ipynb
  Feature-Engineering/Readme.md
Labels: gssoc, level2

#786 Defective Captcha Image Recognition
  Defective Captcha Image Recognition/Dataset/README.md
  Defective Captcha Image Recognition/Images/DenseNet121/26b65009-f08a-4f95-988c-9cb4472d6262.png
  Defective Captcha Image Recognition/Images/DenseNet121/6a74efbb-237f-4ed1-9b1c-53a85ef79c29.png
  Defective Captcha Image Recognition/Images/DenseNet121/ead96295-c9ce-4363-978c-39a87363dca4.png
  Defective Captcha Image Recognition/Images/DenseNet121/fd5fbe70-f1f5-4d32-9f83-7af7b2b96dad.png
  Defective Captcha Image Recognition/Images/EfficientNetB1_predictions/110c0489-de74-4a4a-b156-2e3d0e5d1dcd.png
  Defective Captcha Image Recognition/Images/EfficientNetB1_predictions/351e8e1c-65d4-4459-bbdd-d25640feecd6.png
  Defective Captcha Image Recognition/Images/EfficientNetB1_predictions/57fabd9e-4a15-4f9b-84aa-f6fcdad06f2f.png
  Defective Captcha Image Recognition/Images/EfficientNetB1_predictions/db3e72d8-9787-49c5-ac29-0f883714fbe8-1.png
  Defective Captcha Image Recognition/Images/InceptionV3_predictions/0676b4cc-8572-4478-92e6-c18cf4287d9a.png
  Defective Captcha Image Recognition/Images/InceptionV3_predictions/4b389b70-a176-47d0-bdfd-0930742e88a0.png
  Defective Captcha Image Recognition/Images/InceptionV3_predictions/6ea5b05d-d870-48f7-a546-f4f6db373054.png
  Defective Captcha Image Recognition/Images/InceptionV3_predictions/d00c5e4d-f801-4e56-a7d4-741846506133.png
  Defective Captcha Image Recognition/Images/Resnet50V2_predictions/66ff8a40-eae3-4e85-8754-56c7d315e283.png
  Defective Captcha Image Recognition/Images/Resnet50V2_predictions/73526bcd-3bdb-479a-8d5a-eadf95e39bab.png
  Defective Captcha Image Recognition/Images/Resnet50V2_predictions/8e4ae9ac-48e0-47d6-82ae-1b6cf2513264.png
  Defective Captcha Image Recognition/Images/Resnet50V2_predictions/9dc0755b-8e5c-48fd-9f94-9aaebefa4fa6.png
  Defective Captcha Image Recognition/Images/Xception_predictions/10169ba4-59c7-4a8d-bc3b-6c874085b3f5.png
  Defective Captcha Image Recognition/Images/Xception_predictions/9897dbb4-b870-4efa-b927-8c966741cb1e.png
  Defective Captcha Image Recognition/Images/Xception_predictions/b849f400-11db-456e-bfae-d6eea992561d.png
  Defective Captcha Image Recognition/Images/Xception_predictions/f1bda14c-5c5d-40fa-a382-81ab3114a830.png
  Defective Captcha Image Recognition/Images/bar.png
  Defective Captcha Image Recognition/Images/image_path_distribution.png
  Defective Captcha Image Recognition/Images/pie.png
  Defective Captcha Image Recognition/Models/README.md
  Defective Captcha Image Recognition/Models/models_Defective_Captcha_Image_Recognition_.ipynb
  Defective Captcha Image Recognition/README.md
  Defective Captcha Image Recognition/requirement.txt
Labels: gssoc, level2

#751 Music generation
  Music Generation using LSTM/Music_Generation.ipynb
  Music Generation using LSTM/READme.md
Labels: gssoc, level2

#816 Market basket recommendation system using Apriori
  market-basket-recommendation/Apriori.ipynb
  market-basket-recommendation/app.py
  market-basket-recommendation/data.csv
  market-basket-recommendation/image-1.png
  market-basket-recommendation/readme.md
  market-basket-recommendation/req.txt
Labels: gssoc, level2

#808 Add spam mail prediction
  Spam Mail Classifier/README.md
  Spam Mail Classifier/Spam_Mail_Prediction_using_Machine_Learning (1).ipynb
Labels: gssoc, level1

#723 Web scraping bs4
  Web-Scraping-with-Beautiful-Soup-master/2024-06-09-20-32-07.csv
  Web-Scraping-with-Beautiful-Soup-master/README.md
  Web-Scraping-with-Beautiful-Soup-master/jobs_available.csv
  Web-Scraping-with-Beautiful-Soup-master/newegg_scrape.ipynb
  Web-Scraping-with-Beautiful-Soup-master/popularity_scrape.ipynb
  Web-Scraping-with-Beautiful-Soup-master/realestate_scrape.ipynb
  Web-Scraping-with-Beautiful-Soup-master/scrape_amazon_reviews.ipynb
  Web-Scraping-with-Beautiful-Soup-master/scrape_jobs.ipynb
  Web-Scraping-with-Beautiful-Soup-master/stock_scrape.ipynb
Labels: gssoc, level2

#800 Create Pytorch.md
  Cheat Sheets/Pytorch.md
Labels: gssoc, level1

#828 Regression and Classification Using Auto ML
  AutoML_GSSoC.ipynb
Labels: gssoc, level2

#836 emotion based music recommendation
  emotion-based music recommendtion/README.md
  emotion-based music recommendtion/back.py
  emotion-based music recommendtion/front.py
  emotion-based music recommendtion/requirements.txt
  emotion-based music recommendtion/work.ipynb
Labels: gssoc, level2

#837 Sign language translator
  Sign-Language-Translator/code file sign language translator.ipynb
  Sign-Language-Translator/readme.md
Labels: gssoc, level2

#855 #838 Added Anime Data Analysis and Prediction
  Anime Data Analysis and Prediction/Dataset/All_Anime.csv
  Anime Data Analysis and Prediction/Images/Box plot pr year.png
  Anime Data Analysis and Prediction/Images/Heatmap.png
  Anime Data Analysis and Prediction/Images/Histograms.png
  Anime Data Analysis and Prediction/Images/Normal Distributions.png
  Anime Data Analysis and Prediction/Images/Pairplot.png
  Anime Data Analysis and Prediction/Model/anime_analysis_and_prediction.ipynb
  Anime Data Analysis and Prediction/Model/model_1.pkl
  Anime Data Analysis and Prediction/Model/model_2.pkl
  Anime Data Analysis and Prediction/Readme.md
Labels: gssoc, level2

#841 Feed-forward neural networks (Deep Learning Algorithm)
  Feed-Forward Neural Networks (Deep Learning Algorithm)/README.md
  Feed-Forward Neural Networks (Deep Learning Algorithm)/datasets/gender_submission.csv
  Feed-Forward Neural Networks (Deep Learning Algorithm)/datasets/test.csv
  Feed-Forward Neural Networks (Deep Learning Algorithm)/datasets/train.csv
  Feed-Forward Neural Networks (Deep Learning Algorithm)/feedforwardnet.ipynb
  Feed-Forward Neural Networks (Deep Learning Algorithm)/requirments.txt
  Feed-Forward Neural Networks (Deep Learning Algorithm)/submission.csv
Labels: gssoc, level2

#870 Predict next Sequence of numbers Using LSTM
  Predicting Next Sequence Of Numbers Using LSTM/Dataset/airline-passengers - Sheet1.csv
  Predicting Next Sequence Of Numbers Using LSTM/Model/Predict_next_Sequence_of_numbers_Using_LSTM.ipynb
  Predicting Next Sequence Of Numbers Using LSTM/README.md
  Predicting Next Sequence Of Numbers Using LSTM/requirements.txt
Labels: gssoc, level2

#874 Added Outlier detection
  Outlier Detection/Outlier1.ipynb
  Outlier Detection/Outlier2.ipynb
  Outlier Detection/Readme.md
  Outlier Detection/bhp.csv
  Outlier Detection/weight-height.csv
Labels: gssoc, level2
