Repository Niketkumardheeryan/ML-CaPsule, pull requests merged in 2024-08, with the labels that each got.

#1031 TCS Stock Price Prediction using lstm
  TCS Stock Analysis/Dataset/TCS.csv
  TCS Stock Analysis/Images/Distribution of TCS Daily Returns.png
  TCS Stock Analysis/Images/K-Means Clustering of TCS Stock Price.png
  TCS Stock Analysis/Images/TCS High Stock Prices.png
  TCS Stock Analysis/Images/TCS Stock Price Prediction using LSTM.png
  TCS Stock Analysis/Images/TCS Stock Price.png
  TCS Stock Analysis/Model/TCS_Stock_Price_Prediction_using_LSTM,_K_Means_Clustering_And_Logistic_Regression.ipynb
  TCS Stock Analysis/README.md
  TCS Stock Analysis/requirements.txt
Labels: gssoc, level2

#1035 Anomaly Detection in Transactions using Deep Learning added
  Anomaly Detection in Transactions using Deep Learning/Anomaly_Detection_in_Transactions_using_Deep_Learning.ipynb
  Anomaly Detection in Transactions using Deep Learning/readme.md
  Anomaly Detection in Transactions using Deep Learning/transactions.csv
Labels: gssoc, level1

#1039 added Chess piece classifcation using machine learning
  chess image classification/app.py
  chess image classification/chess_piece_classification.ipynb
  chess image classification/images/avg_image_per_class.png
  chess image classification/images/class_analysis.png
  chess image classification/images/confusion_matrix.png
  chess image classification/images/countplot.png
  chess image classification/images/epochs_Vs_Accuracy_loss.png
  chess image classification/images/prediction_on_real_time_input.png
  chess image classification/images/prediction_on_testing.png
  chess image classification/readme.md
  chess image classification/requirement.txt
  chess image classification/webapp.mp4
Labels: gssoc, level3

#1046 Mobile price prediction model
  Mobile Price Prediction/Dataset/mobile_prices.csv
  Mobile Price Prediction/Images/Mobile Price Chart.png
  Mobile Price Prediction/Images/Mobile Price Trend.png
  Mobile Price Prediction/Model/Mobile_Price_Prediction_Model.ipynb
  Mobile Price Prediction/README.md
Labels: gssoc, level1

#1044 Medical Insurance Cost Prediction added
  Medical Insurance Cost Prediction/Project_11_Medical_Insurance_Cost_Prediction.ipynb
  Medical Insurance Cost Prediction/README.md
  Medical Insurance Cost Prediction/insurance.csv
Labels: gssoc, level1

#1042 Quantitative Finance Strategy Development added
  Quantitative Finance Strategy Development/Quantitative_Finance_Strategy_Development.ipynb
  Quantitative Finance Strategy Development/quantitative_finance_data.csv
  Quantitative Finance Strategy Development/readme.md
Labels: gssoc, level2

#1045 Added Flood Prediction
  Flood_Prediction/Model/Flood_Prediction.ipynb
  Flood_Prediction/README.md
  Flood_Prediction/dataset/India.csv
  Flood_Prediction/images/image.png
  Flood_Prediction/images/image2.png
  Flood_Prediction/requirements.txt
Labels: gssoc, level2

#864 Main commit for Issue #858
  ImageGen using GANs/dcgan_main.py
  ImageGen using GANs/readme.txt
  ImageGen using GANs/results/.DS_Store
  ImageGen using GANs/results/fake_samples_epoch_000.png
  ImageGen using GANs/results/fake_samples_epoch_001.png
  ImageGen using GANs/results/fake_samples_epoch_002.png
  ImageGen using GANs/results/fake_samples_epoch_003.png
  ImageGen using GANs/results/fake_samples_epoch_004.png
  ImageGen using GANs/results/fake_samples_epoch_005.png
  ImageGen using GANs/results/fake_samples_epoch_006.png
  ImageGen using GANs/results/fake_samples_epoch_007.png
  ImageGen using GANs/results/fake_samples_epoch_008.png
  ImageGen using GANs/results/fake_samples_epoch_009.png
  ImageGen using GANs/results/fake_samples_epoch_010.png
  ImageGen using GANs/results/fake_samples_epoch_011.png
  ImageGen using GANs/results/fake_samples_epoch_012.png
  ImageGen using GANs/results/fake_samples_epoch_013.png
  ImageGen using GANs/results/fake_samples_epoch_014.png
  ImageGen using GANs/results/fake_samples_epoch_015.png
  ImageGen using GANs/results/fake_samples_epoch_016.png
  ImageGen using GANs/results/fake_samples_epoch_017.png
  ImageGen using GANs/results/fake_samples_epoch_018.png
  ImageGen using GANs/results/fake_samples_epoch_019.png
  ImageGen using GANs/results/fake_samples_epoch_020.png
  ImageGen using GANs/results/fake_samples_epoch_021.png
  ImageGen using GANs/results/fake_samples_epoch_022.png
  ImageGen using GANs/results/fake_samples_epoch_023.png
  ImageGen using GANs/results/fake_samples_epoch_024.png
  ImageGen using GANs/results/real_samples.png
Labels: gssoc, level2

#865 Website of ML-CaPsule
  website
  website ML-CaPsule/README.md
  website ML-CaPsule/ai.jpeg
  website ML-CaPsule/contribution.html
  website ML-CaPsule/data anal.jpeg
  website ML-CaPsule/data sci.jpeg
  website ML-CaPsule/deep l.jpeg
  website ML-CaPsule/github-api.ipynb
  website ML-CaPsule/home.html
  website ML-CaPsule/index.html
  website ML-CaPsule/indexnewnew.jpg
  website ML-CaPsule/login.html
  website ML-CaPsule/logo.png
  website ML-CaPsule/ml.jpeg
  website ML-CaPsule/readme.md
  website ML-CaPsule/webprojects.html
Labels: gssoc, level2

#1057 optimized the trading strategy based on sentiment analysis added
  optimized the trading strategy based on sentiment analysis/optimized_the_trading_strategy_based_on_sentiment_analysis.ipynb
  optimized the trading strategy based on sentiment analysis/readme.md
  optimized the trading strategy based on sentiment analysis/sentiment_trading_data.csv
Labels: gssoc, level1

#1056 Financial Crisis Warning System added
  Financial Crisis Early Warning System/Financial_Crisis_Early_Warning_System.ipynb
  Financial Crisis Early Warning System/financial_crisis_data.csv
  Financial Crisis Early Warning System/readme.md
Labels: gssoc, level2

#1054 Optimizing_Dividend_Capture_Strategies_Using_Genetics_Algorithms added
  Optimizing_Dividend_Capture_Strategies_Using_Genetics_Algorithms/Optimizing_Dividend_Capture_Strategies_Using_Genetics_Algorithms.ipynb
  Optimizing_Dividend_Capture_Strategies_Using_Genetics_Algorithms/readme.md
  Optimizing_Dividend_Capture_Strategies_Using_Genetics_Algorithms/requirement.txt
Labels: gssoc, level1

#1052 Added Quality Education SDG 04: India Predictive Analysis
  Quality Education SDG 04: Predictive Analysis/Readme.md
  Quality Education SDG 04: Predictive Analysis/Requirements.txt
  Quality Education SDG 04: Predictive Analysis/SDG_4_India.csv
  Quality Education SDG 04: Predictive Analysis/sdg-04-india.ipynb
Labels: gssoc, level2

#1066 railway_person_detection added
  railway_person_detection/.gitignore
  railway_person_detection/README.md
  railway_person_detection/railway_person_detection.py
  railway_person_detection/requirements.txt
Labels: gssoc, level2

#1069 added language learning assistant
  AI_Language_Learning_Assistant/AI-Language-Learning-Assistant.ipynb
  AI_Language_Learning_Assistant/README.md
Labels: gssoc, level1

#1059 Created Plagiarism-detector-using-machine-learning web app
  Plagiarism-detector-using-machine-learning-main/.idea/.gitignore
  Plagiarism-detector-using-machine-learning-main/.idea/Plagiarism-detector-using-machine-learning-main.iml
  Plagiarism-detector-using-machine-learning-main/.idea/inspectionProfiles/Project_Default.xml
  Plagiarism-detector-using-machine-learning-main/.idea/inspectionProfiles/profiles_settings.xml
  Plagiarism-detector-using-machine-learning-main/.idea/misc.xml
  Plagiarism-detector-using-machine-learning-main/.idea/modules.xml
  Plagiarism-detector-using-machine-learning-main/Building Plagiarism checker using Machine Learning.ipynb
  Plagiarism-detector-using-machine-learning-main/README.md
  Plagiarism-detector-using-machine-learning-main/app.py
  Plagiarism-detector-using-machine-learning-main/dataset.csv
  Plagiarism-detector-using-machine-learning-main/model.pkl
  Plagiarism-detector-using-machine-learning-main/templates/index.html
  Plagiarism-detector-using-machine-learning-main/tfidf_vectorizer.pkl
Labels: gssoc, level2
